version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["pnpm", "run", "dev"]
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  cli:
    build: .
    environment:
      - NODE_ENV=development
    command: ["pnpm", "run", "cli"]
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
